service: flask-word

provider:
 name: aws
 runtime: python3.8
 stage: dev
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 wsgi:
   app: main.app	
   packRequirements: false
   pythonBin: python3

functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY /{proxy+}'