name: PyTest
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - name: Set up Python 3.8 
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.8 
    - name: Install dependencies 
      run: | 
        python -m pip install --upgrade pip 
        pip install pylint 
    - name: Lint with pylint
      run: |
        python lint.py
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt pytest
      - uses: cclauss/GitHub-Action-for-pytest@0.5.0
      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
         paths: tests/**
         options: --quiet  # keep pytest quite since there is the action summary
         show: all # show the summary for both successful and failed tests
